// Persona library — 15 distinct seed agents across 5 roles.
// `portrait` is a small key string; rendered as pixel-art in src/draw/portrait.js.
// `tint` is the primary sprite/UI accent color.

export const ROLES = ['frontend', 'backend', 'scrum_master', 'tech_lead', 'solutions_architect'];

export const ROLE_LABELS = {
  frontend: 'Frontend Dev',
  backend: 'Backend Dev',
  scrum_master: 'Scrum Master',
  tech_lead: 'Tech Lead',
  solutions_architect: 'Sol. Architect',
};

export const ROLE_SHORT = {
  frontend: 'FE',
  backend: 'BE',
  scrum_master: 'SM',
  tech_lead: 'TL',
  solutions_architect: 'SA',
};

// Portrait keys describe a procedural face: { hair, skin, accessory }
// hair: short|long|curly|bun|bald|cap|hood|mohawk|braids|ponytail
// skin: 0..4 lightness index
// acc:  none|glasses|shades|headset|beanie|monocle

function p(hair, skin, acc) { return { hair, skin, acc }; }

export const PERSONAS = [
  {
    id: 'fe-mira', displayName: 'Mira Voss', role: 'frontend',
    seniority: 'senior', yearsExperience: 7, salary: 14000,
    preferredStack: ['React', 'TypeScript', 'Tailwind'],
    dislikedStack: ['jQuery', 'PHP'],
    traits: ['perfectionist', 'a11y-zealot', 'pedant'],
    workStyle: 'tdd_first', communicationStyle: 'diplomatic',
    quirks: 'Refuses to merge if Lighthouse < 95.',
    strengths: ['UI polish', 'accessibility'], weaknesses: ['estimation'],
    bio: 'Ex-design-systems lead. Will rewrite your CSS at 2am and feel good about it.',
    portrait: p('long', 2, 'none'), tint: '#ff8fc8',
    skills: { frontend: 78, backend: 22, devops: 18, design: 88, comms: 60, leadership: 40 },
  },
  {
    id: 'fe-rico', displayName: 'Rico Tan', role: 'frontend',
    seniority: 'mid', yearsExperience: 4, salary: 9500,
    preferredStack: ['Vue', 'Nuxt', 'CSS'],
    dislikedStack: ['Class components'],
    traits: ['shipper', 'rockstar', 'chaotic_good'],
    workStyle: 'spike_and_iterate', communicationStyle: 'terse',
    quirks: 'Names every branch after a Pokemon.',
    strengths: ['speed', 'creativity'], weaknesses: ['tests', 'docs'],
    bio: 'Three side-projects on the boil at all times. Ships on Friday afternoons.',
    portrait: p('mohawk', 1, 'shades'), tint: '#9ef0a6',
    skills: { frontend: 70, backend: 35, devops: 25, design: 55, comms: 45, leadership: 30 },
  },
  {
    id: 'fe-juno', displayName: 'Juno Park', role: 'frontend',
    seniority: 'junior', yearsExperience: 1, salary: 5500,
    preferredStack: ['Svelte', 'HTML'],
    dislikedStack: ['Webpack configs'],
    traits: ['mentor-seeker', 'curious'],
    workStyle: 'heads_down', communicationStyle: 'verbose',
    quirks: 'Asks "is this idiomatic?" every standup.',
    strengths: ['learning rate'], weaknesses: ['confidence', 'speed'],
    bio: 'Bootcamp grad. Will surprise you in three sprints.',
    portrait: p('cap', 3, 'glasses'), tint: '#6ad7ff',
    skills: { frontend: 38, backend: 20, devops: 10, design: 30, comms: 50, leadership: 15 },
  },

  {
    id: 'be-saul', displayName: 'Saul Bekele', role: 'backend',
    seniority: 'senior', yearsExperience: 9, salary: 15500,
    preferredStack: ['Go', 'Postgres', 'gRPC'],
    dislikedStack: ['Node.js for backends'],
    traits: ['pedant', 'pragmatist'],
    workStyle: 'tdd_first', communicationStyle: 'blunt',
    quirks: 'Closes PRs with "this will not scale" and walks away.',
    strengths: ['perf', 'data modeling'], weaknesses: ['UI feedback'],
    bio: 'Wrote the migration that saved his last company. Will not let you forget.',
    portrait: p('short', 4, 'none'), tint: '#c79bff',
    skills: { frontend: 18, backend: 92, devops: 75, design: 12, comms: 50, leadership: 55 },
  },
  {
    id: 'be-aiko', displayName: 'Aiko Mori', role: 'backend',
    seniority: 'mid', yearsExperience: 5, salary: 11000,
    preferredStack: ['Python', 'FastAPI', 'Redis'],
    dislikedStack: ['Java'],
    traits: ['mentor', 'shipper'],
    workStyle: 'spike_and_iterate', communicationStyle: 'diplomatic',
    quirks: 'Schedules "rubber-duck Tuesdays".',
    strengths: ['team-fit', 'API design'], weaknesses: ['low-level perf'],
    bio: 'The reason juniors do not cry in standup.',
    portrait: p('bun', 2, 'glasses'), tint: '#5ee0a0',
    skills: { frontend: 30, backend: 78, devops: 55, design: 25, comms: 80, leadership: 65 },
  },
  {
    id: 'be-dax', displayName: 'Dax Olafsson', role: 'backend',
    seniority: 'staff', yearsExperience: 12, salary: 18500,
    preferredStack: ['Rust', 'Kafka', 'Postgres'],
    dislikedStack: ['MongoDB'],
    traits: ['perfectionist', 'pedant', 'mentor'],
    workStyle: 'meeting_heavy', communicationStyle: 'verbose',
    quirks: 'Writes ADRs for choosing lunch.',
    strengths: ['architecture', 'rigor'], weaknesses: ['shipping speed'],
    bio: 'If you make a decision without a doc, he writes one for you.',
    portrait: p('hood', 1, 'monocle'), tint: '#ffd166',
    skills: { frontend: 25, backend: 95, devops: 88, design: 40, comms: 70, leadership: 80 },
  },

  {
    id: 'sm-priya', displayName: 'Priya Rao', role: 'scrum_master',
    seniority: 'senior', yearsExperience: 8, salary: 12500,
    preferredStack: ['Jira', 'Notion', 'Miro'],
    dislikedStack: ['email threads'],
    traits: ['diplomatic', 'shipper', 'mentor'],
    workStyle: 'meeting_heavy', communicationStyle: 'diplomatic',
    quirks: 'Has a kanban for her kanbans.',
    strengths: ['velocity', 'retros'], weaknesses: ['technical depth'],
    bio: 'Will end a meeting on time. Yes, that one.',
    portrait: p('braids', 3, 'none'), tint: '#9ef0a6',
    skills: { frontend: 12, backend: 14, devops: 10, design: 35, comms: 92, leadership: 88 },
  },
  {
    id: 'sm-ben', displayName: 'Ben Cortez', role: 'scrum_master',
    seniority: 'mid', yearsExperience: 4, salary: 8500,
    preferredStack: ['Linear', 'Slack'],
    dislikedStack: ['Gantt charts'],
    traits: ['chaotic_good', 'shipper'],
    workStyle: 'heads_down', communicationStyle: 'terse',
    quirks: 'Calls every meeting "a quick sync" — they are 47 minutes.',
    strengths: ['unblocking'], weaknesses: ['process discipline'],
    bio: 'Recovering startup founder. Allergic to bureaucracy.',
    portrait: p('short', 2, 'beanie'), tint: '#6ad7ff',
    skills: { frontend: 15, backend: 18, devops: 12, design: 25, comms: 78, leadership: 60 },
  },
  {
    id: 'sm-zara', displayName: 'Zara Hill', role: 'scrum_master',
    seniority: 'junior', yearsExperience: 2, salary: 5800,
    preferredStack: ['Notion', 'Trello'],
    dislikedStack: ['Excel'],
    traits: ['curious', 'pedant'],
    workStyle: 'tdd_first', communicationStyle: 'verbose',
    quirks: 'Reads SCRUM Guide on weekends. For fun.',
    strengths: ['ceremonies'], weaknesses: ['conflict resolution'],
    bio: 'Knows the entire Agile Manifesto by heart.',
    portrait: p('ponytail', 1, 'glasses'), tint: '#ff8fc8',
    skills: { frontend: 10, backend: 10, devops: 8, design: 22, comms: 65, leadership: 38 },
  },

  {
    id: 'tl-marcus', displayName: 'Marcus Vale', role: 'tech_lead',
    seniority: 'staff', yearsExperience: 11, salary: 17500,
    preferredStack: ['TypeScript', 'Next.js', 'Postgres'],
    dislikedStack: ['legacy AngularJS'],
    traits: ['mentor', 'pragmatist', 'pedant'],
    workStyle: 'meeting_heavy', communicationStyle: 'diplomatic',
    quirks: 'Prefaces hard feedback with "with love...".',
    strengths: ['code review', 'mentorship'], weaknesses: ['IC velocity'],
    bio: 'Genuinely cares about your career. Will still block your PR.',
    portrait: p('curly', 4, 'glasses'), tint: '#ffce5b',
    skills: { frontend: 70, backend: 75, devops: 60, design: 50, comms: 85, leadership: 90 },
  },
  {
    id: 'tl-vera', displayName: 'Vera Lin', role: 'tech_lead',
    seniority: 'senior', yearsExperience: 8, salary: 15000,
    preferredStack: ['Go', 'Kubernetes', 'gRPC'],
    dislikedStack: ['monorepos with no tooling'],
    traits: ['blunt', 'perfectionist'],
    workStyle: 'tdd_first', communicationStyle: 'blunt',
    quirks: 'Has a 27-tab "must read" Slack canvas.',
    strengths: ['system design', 'standards'], weaknesses: ['warmth'],
    bio: 'You will learn from her. You may also cry.',
    portrait: p('long', 2, 'shades'), tint: '#ff6b81',
    skills: { frontend: 50, backend: 88, devops: 82, design: 35, comms: 60, leadership: 78 },
  },
  {
    id: 'tl-omar', displayName: 'Omar Idris', role: 'tech_lead',
    seniority: 'senior', yearsExperience: 7, salary: 14000,
    preferredStack: ['Elixir', 'Phoenix', 'LiveView'],
    dislikedStack: ['microservices for 3 users'],
    traits: ['shipper', 'chaotic_good', 'mentor'],
    workStyle: 'spike_and_iterate', communicationStyle: 'verbose',
    quirks: 'Demos in standup. Live. Always.',
    strengths: ['prototyping', 'energy'], weaknesses: ['documentation'],
    bio: 'The reason your demo is good and your tests are not.',
    portrait: p('short', 3, 'headset'), tint: '#5ee0a0',
    skills: { frontend: 65, backend: 80, devops: 55, design: 60, comms: 75, leadership: 70 },
  },

  {
    id: 'sa-ines', displayName: 'Ines Calder', role: 'solutions_architect',
    seniority: 'staff', yearsExperience: 14, salary: 19000,
    preferredStack: ['AWS', 'Terraform', 'EventBridge'],
    dislikedStack: ['undocumented infra'],
    traits: ['perfectionist', 'mentor', 'diplomatic'],
    workStyle: 'meeting_heavy', communicationStyle: 'diplomatic',
    quirks: 'Has a t-shirt that says "Have you considered events?"',
    strengths: ['cloud', 'cost modeling'], weaknesses: ['IC code'],
    bio: 'Three diagrams in, three diagrams out.',
    portrait: p('bun', 2, 'glasses'), tint: '#c79bff',
    skills: { frontend: 30, backend: 80, devops: 92, design: 60, comms: 88, leadership: 92 },
  },
  {
    id: 'sa-finn', displayName: "Finn O'Hara", role: 'solutions_architect',
    seniority: 'senior', yearsExperience: 9, salary: 16500,
    preferredStack: ['GCP', 'BigQuery', 'Dataflow'],
    dislikedStack: ['"just put it in S3"'],
    traits: ['pedant', 'pragmatist'],
    workStyle: 'heads_down', communicationStyle: 'terse',
    quirks: 'Will not start without an SLA.',
    strengths: ['data platforms'], weaknesses: ['quick turnarounds'],
    bio: 'Old-school. The diagrams are pencil. They are correct.',
    portrait: p('bald', 1, 'monocle'), tint: '#6ad7ff',
    skills: { frontend: 25, backend: 75, devops: 88, design: 55, comms: 65, leadership: 78 },
  },
  {
    id: 'sa-nyla', displayName: 'Nyla Brooks', role: 'solutions_architect',
    seniority: 'senior', yearsExperience: 8, salary: 15500,
    preferredStack: ['Multi-cloud', 'CDK', 'Edge'],
    dislikedStack: ['snowflake servers'],
    traits: ['rockstar', 'mentor'],
    workStyle: 'spike_and_iterate', communicationStyle: 'verbose',
    quirks: 'Owns six laptops. Two are for show.',
    strengths: ['edge', 'energy'], weaknesses: ['cost'],
    bio: 'Your CDN bill is bigger now. So is your demo.',
    portrait: p('mohawk', 4, 'shades'), tint: '#ff8fc8',
    skills: { frontend: 55, backend: 70, devops: 85, design: 70, comms: 80, leadership: 75 },
  },
];

// candidate-only personas (people not on the team yet)
export const CANDIDATE_POOL = [
  {
    id: 'cand-iris', displayName: 'Iris Wen', role: 'frontend',
    seniority: 'senior', yearsExperience: 8, salary: 13500,
    preferredStack: ['Solid.js', 'TypeScript'], dislikedStack: ['React'],
    traits: ['blunt', 'perfectionist'], workStyle: 'heads_down', communicationStyle: 'blunt',
    quirks: 'Does not do standup. Reads the notes after.',
    strengths: ['perf', 'rigor'], weaknesses: ['team rituals'],
    bio: 'Built a framework. You have heard of it.',
    portrait: p('long', 2, 'shades'), tint: '#ff6b81',
    skills: { frontend: 90, backend: 40, devops: 30, design: 70, comms: 30, leadership: 45 },
  },
  {
    id: 'cand-tomo', displayName: 'Tomo Ishida', role: 'backend',
    seniority: 'senior', yearsExperience: 9, salary: 15000,
    preferredStack: ['Java', 'Spring', 'Cassandra'], dislikedStack: ['Python'],
    traits: ['mentor', 'pragmatist', 'diplomatic'], workStyle: 'tdd_first', communicationStyle: 'diplomatic',
    quirks: 'Brings homemade onigiri to onsites.',
    strengths: ['stability', 'mentorship'], weaknesses: ['novelty'],
    bio: 'Will keep your service up at 3am on a holiday.',
    portrait: p('short', 2, 'none'), tint: '#5ee0a0',
    skills: { frontend: 25, backend: 88, devops: 72, design: 22, comms: 78, leadership: 80 },
  },
  {
    id: 'cand-ren', displayName: 'Ren Halberd', role: 'tech_lead',
    seniority: 'senior', yearsExperience: 7, salary: 14500,
    preferredStack: ['Rust', 'WASM', 'Edge'], dislikedStack: ['legacy CRUD'],
    traits: ['rockstar', 'chaotic_good', 'shipper'], workStyle: 'spike_and_iterate', communicationStyle: 'terse',
    quirks: 'Live-codes on stream. Wins.',
    strengths: ['demos', 'innovation'], weaknesses: ['process'],
    bio: 'Half genius, half disaster. You decide which half.',
    portrait: p('mohawk', 1, 'shades'), tint: '#c79bff',
    skills: { frontend: 75, backend: 85, devops: 70, design: 55, comms: 50, leadership: 60 },
  },
  {
    id: 'cand-elin', displayName: 'Elin Nordberg', role: 'scrum_master',
    seniority: 'senior', yearsExperience: 7, salary: 11500,
    preferredStack: ['Linear', 'GitHub Projects'], dislikedStack: ['Jira'],
    traits: ['blunt', 'shipper'], workStyle: 'heads_down', communicationStyle: 'blunt',
    quirks: 'Cancels three meetings on day one.',
    strengths: ['focus', 'unblocking'], weaknesses: ['warmth'],
    bio: 'Your calendar will hate her. Your output will love her.',
    portrait: p('ponytail', 1, 'none'), tint: '#ffd166',
    skills: { frontend: 12, backend: 12, devops: 12, design: 30, comms: 75, leadership: 82 },
  },
  {
    id: 'cand-luca', displayName: 'Luca Pereira', role: 'solutions_architect',
    seniority: 'senior', yearsExperience: 8, salary: 16000,
    preferredStack: ['Edge', 'Cloudflare', 'D1'], dislikedStack: ['on-prem'],
    traits: ['shipper', 'pragmatist'], workStyle: 'spike_and_iterate', communicationStyle: 'diplomatic',
    quirks: 'Whiteboard sketches end up online.',
    strengths: ['cost', 'edge'], weaknesses: ['enterprise patience'],
    bio: 'Your AWS bill drops 40%. So does your patience for legacy.',
    portrait: p('curly', 3, 'glasses'), tint: '#9ef0a6',
    skills: { frontend: 40, backend: 75, devops: 90, design: 65, comms: 80, leadership: 78 },
  },
  {
    id: 'cand-yara', displayName: 'Yara Singh', role: 'frontend',
    seniority: 'junior', yearsExperience: 2, salary: 6500,
    preferredStack: ['React', 'TS'], dislikedStack: ['CSS-in-JS'],
    traits: ['curious', 'shipper', 'mentor-seeker'], workStyle: 'tdd_first', communicationStyle: 'verbose',
    quirks: 'Writes the best PR descriptions on the team.',
    strengths: ['learning', 'docs'], weaknesses: ['speed'],
    bio: 'Quiet engine of any team she joins.',
    portrait: p('braids', 4, 'headset'), tint: '#6ad7ff',
    skills: { frontend: 50, backend: 30, devops: 18, design: 45, comms: 70, leadership: 25 },
  },
  {
    id: 'cand-bram', displayName: 'Bram Janssen', role: 'backend',
    seniority: 'staff', yearsExperience: 13, salary: 19500,
    preferredStack: ['Erlang', 'OTP', 'Postgres'], dislikedStack: ['serverless'],
    traits: ['pedant', 'perfectionist', 'mentor'], workStyle: 'meeting_heavy', communicationStyle: 'verbose',
    quirks: 'Names pets after Erlang processes.',
    strengths: ['fault tolerance'], weaknesses: ['hiring you'],
    bio: 'If your system goes down, his did not.',
    portrait: p('hood', 2, 'monocle'), tint: '#ffce5b',
    skills: { frontend: 15, backend: 96, devops: 85, design: 25, comms: 65, leadership: 85 },
  },
  {
    id: 'cand-noor', displayName: 'Noor Hadid', role: 'tech_lead',
    seniority: 'senior', yearsExperience: 8, salary: 14800,
    preferredStack: ['React', 'Node', 'Redis'], dislikedStack: ['monoliths'],
    traits: ['diplomatic', 'mentor', 'shipper'], workStyle: 'meeting_heavy', communicationStyle: 'diplomatic',
    quirks: 'Brings homemade baklava to retros.',
    strengths: ['team dynamics'], weaknesses: ['saying no'],
    bio: 'Builds teams that do not want to leave.',
    portrait: p('long', 3, 'none'), tint: '#ff8fc8',
    skills: { frontend: 70, backend: 70, devops: 55, design: 55, comms: 88, leadership: 88 },
  },
];

// Tech tickets for the calculator product
export const SEED_BACKLOG = [
  { id: 'CAL-1', title: 'Project scaffold + CI', estimate: 3, role: 'tech_lead' },
  { id: 'CAL-2', title: 'Number pad UI', estimate: 2, role: 'frontend' },
  { id: 'CAL-3', title: 'Expression parser', estimate: 5, role: 'backend' },
  { id: 'CAL-4', title: 'Operator precedence', estimate: 3, role: 'backend' },
  { id: 'CAL-5', title: 'History panel', estimate: 2, role: 'frontend' },
  { id: 'CAL-6', title: 'Keyboard shortcuts', estimate: 2, role: 'frontend' },
  { id: 'CAL-7', title: 'Theme system', estimate: 3, role: 'frontend' },
  { id: 'CAL-8', title: 'Scientific mode', estimate: 5, role: 'backend' },
  { id: 'CAL-9', title: 'Cloud sync API', estimate: 5, role: 'solutions_architect' },
  { id: 'CAL-10', title: 'A11y pass', estimate: 2, role: 'frontend' },
  { id: 'CAL-11', title: 'Standup automation bot', estimate: 3, role: 'scrum_master' },
  { id: 'CAL-12', title: 'Architecture ADR', estimate: 2, role: 'solutions_architect' },
];
